import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web8 from "../public/web8.png";
import web9 from "../public/web9.png";
import {motion} from "framer-motion";
import boot from "../public/boot.png";
import css from "../public/css.png";
import figma from "../public/figma.png";
import gh from "../public/gh.png";
import html from "../public/html.png";
import jira from "../public/jira.png";
import js from "../public/js.png";
import react from "../public/react.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Artem Nefedov - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">PORTFOLIO</h1>
            <ul className="flex items-center">
              <motion.li whileHover={{scale:1.2}}>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </motion.li>
              <motion.li whileHover={{scale:1.1}}>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://www.linkedin.com/in/alex-nefedov/" target="_blank" rel="noreferrer">
                  Contact me
                </a>
              </motion.li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Artem Nefedov
            </h2>
            <h3 className="text-2xl py-2 font-mdeium dark:text-white md:text-3xl">
              Front-end Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Front-end Engineer providing services for programming and design content
              needs. Join me down below and let us get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <motion.a whileHover={{scale: 1.2, transition: {duration: .2}}} href="https://github.com/neffedych"><AiFillGithub /></motion.a>
              <motion.a whileHover={{scale: 1.2, transition: {duration: .2}}} href="https://www.linkedin.com/in/alex-nefedov/"><AiFillLinkedin /></motion.a>
              <motion.a whileHover={{scale: 1.2, transition: {duration: .2}}} href="mailto:alexnefedovqa@gmail.com"> <AiFillMail/></motion.a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <div className="hor-line">
              <div className="hor-line-left dark:bg-white"></div>
              <h3 className="text-3xl py-1 font-bold dark:text-white ">Services</h3>
              <div className="hor-line-right dark:bg-white"></div>
            </div>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 image__services">
              <motion.div whileHover={{scale:1.2}}>
              <Image src={design} width={100} height={100} />
              </motion.div>
              <h3 className="text-lg font-bold pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="font-bold py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-500 py-1">HTML</p>
              <p className="text-gray-500 py-1">CSS</p>
              <p className="text-gray-500 py-1">Bootstrap 5</p>
              <p className="text-gray-500 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <motion.div whileHover={{scale:1.2}}>
                <Image className="service-btn" src={code} width={100} height={100} />
              </motion.div>
              <h3 className="text-lg font-bold pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Le us make it a
                reality.
              </p>
              <h4 className="font-bold py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-500 py-1">JavaScript</p>
              <p className="text-gray-500 py-1">React</p>
              <p className="text-gray-500 py-1">Next JS</p>
              <p className="text-gray-500 py-1">GitHub</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <motion.div whileHover={{scale:1.2}}>
                <Image className="service-btn" src={consulting} width={100} height={100} />
              </motion.div>
              <h3 className="text-lg font-bold pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="font-bold py-4 text-teal-600 ">Tools I Use</h4>
              <p className="text-gray-500 py-1">JIRA/Confluence</p>
              <p className="text-gray-500 py-1">MongoDB</p>
              <p className="text-gray-500 py-1">Photoshop</p>
              <p className="text-gray-500 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section className="skills">
          <div className="hor-line">
            <div className="hor-line-left dark:bg-white"></div>
            <h3 className="text-3xl py-1 font-bold dark:text-white ">Skills</h3>
            <div className="hor-line-right dark:bg-white"></div>
          </div>
          
          <div className="skillset">
            <div className="tooltip" dataName="JavaScript">
              <Image src={js} />
            </div>
            
            <div className="tooltip" dataName="React">
              <Image src={react} />
            </div>

            <div className="tooltip" dataName="CSS">
              <Image src={css} />
            </div>
            <div className="tooltip" dataName="HTML">
              <Image src={html} />
            </div>
            <div className="tooltip" dataName="Bootstrap">
              <Image src={boot} />
            </div>
            <div className="tooltip " dataName="GitHub">
              <Image src={gh} />
            </div>
            <div className="tooltip" dataName="Figma">
              <Image src={figma} />
            </div>
            <div className="tooltip" dataName="Jira/Confluence">
              <Image src={jira} />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <div className="hor-line">
              <div className="hor-line-left dark:bg-white"></div>
              <h3 className="text-3xl py-1 font-bold dark:text-white ">Portfolio</h3> 
              <div className="hor-line-right dark:bg-white"></div>
            </div>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <motion.div className="basis-1/3 flex-1 " whileHover={{scale: .9, transition: {duration: .3}}}>
              <a  target={'_blank'} href="https://eccomerce-artem-nefedov.netlify.app/#/Home" rel="noreferrer">

                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web9}
                />
              </a>
            </motion.div>
            <motion.div className="basis-1/3 flex-1" whileHover={{scale: .9, transition: {duration: .3}}}>
              <a target={'_blank'} href="https://the-mint-artem-nefedov.netlify.app/" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web8}
                />
              </a>
            </motion.div>
            <motion.div className="basis-1/3 flex-1" whileHover={{scale: .9, transition: {duration: .3}}}>
              <a target={'_blank'} href="https://cryptocurrency-artem-nefedov.netlify.app/" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </motion.div>
            <motion.div className="basis-1/3 flex-1" whileHover={{scale: .9, transition: {duration: .3}}}>
              <a target={'_blank'} href="https://neffedych.github.io/movie_app/movie_app/" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web4}
                />
              </a>
            </motion.div>
            <motion.div className="basis-1/3 flex-1" whileHover={{scale: .9, transition: {duration: .3}}}>
              <a target={'_blank'} href="https://neffedych.github.io/World-Cup-Quiz/world_cup/" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                />
              </a>
            </motion.div>
            <motion.div className="basis-1/3 flex-1" whileHover={{scale: .9, transition: {duration: .3}}}>
              <a target={'_blank'} href="https://rolling-scopes-school.github.io/neffedych-JSFE2022Q3/online-zoo/" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web6}
                />
              </a>
            </motion.div>
          </div>
        </section>
      </main>

      <footer className="dark:bg-gray-900">
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
              <motion.a whileHover={{scale: 1.2, transition: {duration: .2}}} href="https://github.com/neffedych"><AiFillGithub /></motion.a>
              <motion.a whileHover={{scale: 1.2, transition: {duration: .2}}} href="https://www.linkedin.com/in/alex-nefedov/"><AiFillLinkedin /></motion.a>
              <motion.a whileHover={{scale: 1.2, transition: {duration: .2}}} href="mailto:alexnefedovqa@gmail.com"> <AiFillMail/></motion.a>
            </div>
            <p className="footer-p dark:text-white">Made with love by Artem Nefedov. ©Copyright 2023 All Rights are reserved.</p>
      </footer>
    </div>
  );
}
